### ISSUE TITLE
net.opecko.logback.appenders.flume.FlumeAvroManager: Unable to create Transceiver error

### ISSUE THREAD

**Issue by lalkhum** [jopecko/logback-flume-ng#1]
I upgraded my java version from 1.7 to 1.8 and I got the error as in title.

I wonder if it is to do with my upgrade? Or something else?
Error details:
2015-09-22 15:00:00,370 - [ERROR] - from net.opecko.logback.appenders.flume.FlumeAvroManager in main 
Unable to create transceiver
java.io.IOException: Error connecting to localhost/127.0.0.1:4141
    at org.apache.avro.ipc.NettyTransceiver.getChannel(NettyTransceiver.java:261) ~[org.apache.avro.avro-ipc-1.7.2.jar:1.7.2]
    at org.apache.avro.ipc.NettyTransceiver.<init>(NettyTransceiver.java:203) ~[org.apache.avro.avro-ipc-1.7.2.jar:1.7.2]
    at org.apache.avro.ipc.NettyTransceiver.<init>(NettyTransceiver.java:152) ~[org.apache.avro.avro-ipc-1.7.2.jar:1.7.2]

...

**Comment by jopecko** [comment]
@lalkhum I'm not sure when I'll be able to look into this. I created this fork of the Log4j2 flume appender over 2 years ago when I was working for a different company and was actively using it. Having since moved on, I haven't touched this project in quite some time. I'll make every effort to try to carve out some time, however, I'm unable to make any promises or commit to any timelines. Thank you very much for the report. Please let me know if you make any progress in the meantime.
